sudo: false

language: node_js

node_js:
  - 6
  - 7
  - 8

notifications:
  email:
    on_success: never
    on_failure: change

cache:
  directories:

before_script:
  - yarn

script:
  - yarn test
